// Runs before esbuild. Reads icons.json (curated from this design system's
// actual lucide-react usage — the /iconography docs page's showcase plus
// every icon literally imported by a real component) and pulls each icon's
// raw SVG from lucide-static into a generated TS module the plugin bundles.
// Fails loudly on a missing icon rather than silently dropping it.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const dir = path.dirname(fileURLToPath(import.meta.url));
const iconNames = JSON.parse(readFileSync(path.join(dir, "icons.json"), "utf8"));

const entries = iconNames.map((name) => {
  const svgPath = path.join(dir, "node_modules", "lucide-static", "icons", `${name}.svg`);
  let svg;
  try {
    svg = readFileSync(svgPath, "utf8");
  } catch {
    throw new Error(`generate-icons: no lucide-static icon found for "${name}" (looked for ${svgPath})`);
  }
  // Strip the license comment line; keep the rest as-is.
  svg = svg.replace(/<!--.*?-->\s*/s, "");
  return `  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`;
});

const output = `// GENERATED by generate-icons.mjs — do not edit by hand.
// Re-run \`npm run build\` (or just the generator) after changing icons.json.

export const iconSvgs: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(path.join(dir, "src", "generated-icons.ts"), output);
console.log(`generate-icons: wrote ${iconNames.length} icons to src/generated-icons.ts`);
